import {HttpError,cleanToken,cleanUsername,usernameKey,parseJsonArray,pacificDate,addDaysDateKey,levelFromPoints,accountObject,accountsSheet,sheetValues,appendValues,findAccountByToken,findAccountByUsername,padRow,saveAccountRow,ensureSheet} from './common.js';
import {CARD_CATALOG} from './cards.js';
import {SHOP_CATALOG,PACK_CATALOG,SET_META,RARITIES,SLOT_ODDS,GAME_POINTS,GAME_COINS,ACHIEVEMENT_BONUSES,TITLE_LEVELS,FREE_PACK_ODDS} from './catalog.js';
const METHODS=new Set(['registerFootballHQAccount','getFootballHQStableGuestIdentity','getFootballHQIdentityDiagnostic','findFootballHQKnownAccountByUsername','claimFootballHQAccountForBrowser','renameFootballHQAccount','ensureFootballHQRecoveryCode','recoverFootballHQAccountWithCode','acknowledgeFootballHQWelcome','getFootballHQShop','getFootballHQDailyRewards','claimFootballHQDailyReward','getFootballHQCollections','purchaseFootballHQShopItem','openFootballHQPack','updateFootballHQCosmetic','submitFootballHQAchievementAwards','updateFootballHQTitle','updateFootballHQAvatar','submitFootballHQDailyResult']);
export function handlesAccountRpc(m){return METHODS.has(String(m||''));}
export async function handleAccountRpc(method,args,env){switch(String(method||'')){case 'registerFootballHQAccount':return registerAccount(args?.[0],args?.[1],env);case 'getFootballHQStableGuestIdentity':return stableGuest(args?.[0],env);case 'getFootballHQIdentityDiagnostic':return identityDiagnostic(args?.[0],env);case 'findFootballHQKnownAccountByUsername':return findKnown(args?.[0],args?.[1],env);case 'claimFootballHQAccountForBrowser':return (await findAccountByToken(String(args?.[0]||''),env))?.profile||null;case 'renameFootballHQAccount':return renameAccount(args?.[0],args?.[1],env);case 'ensureFootballHQRecoveryCode':return ensureRecoveryCode(args?.[0],env);case 'recoverFootballHQAccountWithCode':return recoverWithCode(args?.[0],args?.[1],env);case 'acknowledgeFootballHQWelcome':return acknowledgeWelcome(args?.[0],env);case 'getFootballHQShop':return getShop(args?.[0],env);case 'getFootballHQDailyRewards':return getDailyRewards(args?.[0],env);case 'claimFootballHQDailyReward':return claimDailyReward(args?.[0],env);case 'getFootballHQCollections':return getCollections(args?.[0],env);case 'purchaseFootballHQShopItem':return purchaseShopItem(args?.[0],env);case 'openFootballHQPack':return openPack(args?.[0],env);case 'updateFootballHQCosmetic':return updateCosmetic(args?.[0],env);case 'submitFootballHQAchievementAwards':return awardAchievements(args?.[0],env);case 'updateFootballHQTitle':return updateTitle(args?.[0],env);case 'updateFootballHQAvatar':return updateAvatar(args?.[0],env);case 'submitFootballHQDailyResult':return submitDailyResult(args?.[0],env);default:return null;}}
async function registerAccount(username,token,env){username=cleanUsername(username);token=cleanToken(token);const rows=await sheetValues(env,`${accountsSheet(env)}!A2:W`),key=usernameKey(username);const ti=rows.findIndex(r=>String(r[0]||'')===token),ni=rows.findIndex(r=>usernameKey(r[2]||r[1])===key);if(ni>=0&&ni!==ti)throw new HttpError(409,'That username is already taken.');if(ti>=0){const row=padRow(rows[ti]);row[1]=username;row[2]=key;grantWelcome(row);grantPassCoins(row);return saveAccountRow(env,ti+2,row);}const row=[token,username,key,0,0,0,'',new Date().toISOString(),'','','','','[]','',0,'[]','','','[]',0,true,'[]',''];grantWelcome(row);await appendValues(env,`${accountsSheet(env)}!A:W`,[row]);return accountObject(row);}
async function stableGuest(token,env){token=cleanToken(token);const a=await findAccountByToken(token,env);if(a)return a.profile;const tail=token.replace(/[^A-Za-z0-9]/g,'').slice(-6).toUpperCase();return registerAccount('Guest-'+(tail||'PLAYER'),token,env);}
async function identityDiagnostic(token,env){try{const a=await findAccountByToken(token,env);return {token:String(token||''),found:!!a,username:a?.profile?.username||'',points:Number(a?.profile?.points||0),totalDailies:Number(a?.profile?.totalDailies||0)}}catch{return {token:String(token||''),found:false,username:'',points:0,totalDailies:0}}}
async function findKnown(tokens,username,env){const set=new Set((Array.isArray(tokens)?tokens:[]).map(String));const a=await findAccountByUsername(username,env);return a&&set.has(a.profile.token)?a.profile:null;}
async function renameAccount(token,name,env){const a=await findAccountByToken(token,env);if(!a)throw new HttpError(404,'Account not found.');name=cleanUsername(name);const other=await findAccountByUsername(name,env);if(other&&other.profile.token!==a.profile.token)throw new HttpError(409,'That username is already taken.');a.row[1]=name;a.row[2]=usernameKey(name);return saveAccountRow(env,a.sheetRow,a.row);}
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function recoveryHash(username,code){return sha256(usernameKey(username)+'|'+String(code||'').trim().toUpperCase());}
function newRecoveryCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',raw=crypto.randomUUID().replace(/-/g,'').toUpperCase();let o='';for(let i=0;i<8;i++)o+=chars[parseInt(raw[i],16)%chars.length];return o.slice(0,4)+'-'+o.slice(4);}
async function ensureRecoveryCode(token,env){const a=await findAccountByToken(token,env);if(!a)throw new HttpError(404,'Account not found.');if(String(a.row[10]||''))return {recoveryCode:'',alreadyCreated:true};const code=newRecoveryCode();a.row[10]=await recoveryHash(a.row[1],code);a.row[11]=new Date().toISOString();await saveAccountRow(env,a.sheetRow,a.row);return {recoveryCode:code,alreadyCreated:false};}
async function recoverWithCode(username,code,env){username=cleanUsername(username);code=String(code||'').trim().toUpperCase().replace(/-/g,'');if(!/^[A-Z2-9]{8}$/.test(code))throw new HttpError(400,'Invalid recovery code.');const a=await findAccountByUsername(username,env);if(!a)throw new HttpError(403,'Username or recovery code is incorrect.');const formatted=code.slice(0,4)+'-'+code.slice(4);if(!a.row[10]||a.row[10]!==await recoveryHash(a.row[1],formatted))throw new HttpError(403,'Username or recovery code is incorrect.');return a.profile;}
function grantWelcome(row){let inv=parseJsonArray(row[15]);if(inv.some(x=>x&&(x.id==='welcome|v79'||x.id==='welcome|v78')))return;row[14]=Number(row[14]||0)+500;inv.push({id:'welcome|v79',type:'welcome',value:500,name:'TURF Welcome',source:'Welcome',rarity:'currency',presented:false,earnedAt:pacificDate()});row[15]=JSON.stringify(inv);}
function passCoinAmount(l){if(l<=1)return 0;if(l<10)return 50;if(l<25)return 75;if(l<50)return 100;if(l<75)return 125;return 150;}function passSpecial(l){return [2,3,5,7,10,12,15,18,20,25,30,35,40,50,60,70,75,85,90,100].includes(Number(l));}
export function grantPassCoins(row){const level=levelFromPoints(Number(row[3]||0));let coins=Number(row[14]||0),inv=parseJsonArray(row[15]),changed=false;for(let l=2;l<=level;l++){if(passSpecial(l))continue;const id='passcoin|'+l;if(inv.some(x=>x&&x.id===id))continue;const amount=passCoinAmount(l);if(amount){coins+=amount;inv.push({id,type:'coins',value:amount,name:amount+' TURF Coins',source:'TURF Pass',level:l});changed=true;}}if(changed){row[14]=coins;row[15]=JSON.stringify(inv);}}
async function acknowledgeWelcome(token,env){const a=await findAccountByToken(token,env);if(!a)throw new HttpError(404,'Account not found.');const inv=parseJsonArray(a.row[15]);const x=inv.find(v=>v&&(v.id==='welcome|v79'||v.id==='welcome|v78'));if(x&&x.presented!==true){x.presented=true;x.presentedAt=new Date().toISOString();a.row[15]=JSON.stringify(inv);}const profile=await saveAccountRow(env,a.sheetRow,a.row);return {welcomeBonusGranted:false,amount:0,balance:Number(a.row[14]||0),profile};}
export async function loadAccountForMutation(token,env){const a=await findAccountByToken(cleanToken(token),env);if(!a)throw new HttpError(404,'Account not found.');grantWelcome(a.row);grantPassCoins(a.row);return a;}
async function getShop(token,env){const a=await loadAccountForMutation(token,env);const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,items:Object.values(SHOP_CATALOG),packs:Object.values(PACK_CATALOG),cards:CARD_CATALOG};}
function dailyState(row){const inv=parseJsonArray(row[15]),date=pacificDate();return {date,giftClaimed:inv.some(x=>x?.id==='dailygift|'+date),packClaimed:inv.some(x=>x?.id==='freepack|'+date),giftCoins:50,nextReset:'12:00 AM Pacific'};}
async function getDailyRewards(token,env){const a=await loadAccountForMutation(token,env);const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,state:dailyState(a.row)};}
function pickWeighted(weights){let total=0;for(const r of RARITIES)total+=Number(weights[r]||0);let roll=Math.random()*total,acc=0;for(const r of RARITIES){acc+=Number(weights[r]||0);if(roll<=acc)return r;}return 'common';}
function randomCard(collection,slot){const rarity=pickWeighted(SLOT_ODDS[slot]||SLOT_ODDS.rookie);let pool=CARD_CATALOG.filter(x=>x.rarity===rarity);if(!pool.length)pool=CARD_CATALOG;const unowned=pool.filter(x=>!collection.includes(x.id));const src=unowned.length?unowned:pool;return src[Math.floor(Math.random()*src.length)];}
function duplicateCoins(r){return r==='signature'?225:r==='obsidian'?120:r==='legendary'?75:r==='epic'?45:r==='rare'?28:r==='uncommon'?20:12;}
function setCompletion(collection,inventory,coins){const bonus=[],owned=new Set(collection);for(const [setName,meta] of Object.entries(SET_META)){const cards=CARD_CATALOG.filter(c=>c.set===setName);if(!cards.length||!cards.every(c=>owned.has(c.id)))continue;const id='setcomplete|'+setName;if(inventory.some(x=>x?.id===id))continue;const reward={id,type:'title',value:meta.rewardTitle,name:meta.rewardTitle,source:'Collection Set',rarity:'legendary'};inventory.push(reward);coins+=Number(meta.rewardCoins||0);bonus.push({type:'coins',value:Number(meta.rewardCoins||0),name:setName+' Complete +'+meta.rewardCoins+' Coins',rarity:'currency'},reward);}return {collection,inventory,coins,bonus};}
async function claimDailyReward(payload,env){payload=payload||{};const a=await loadAccountForMutation(payload.token,env),state=dailyState(a.row),kind=String(payload.kind||''),date=state.date;let inv=parseJsonArray(a.row[15]),collection=parseJsonArray(a.row[21]),coins=Number(a.row[14]||0),reward=null;if(kind==='gift'){if(state.giftClaimed)return {profile:a.profile,state,alreadyClaimed:true};coins+=50;inv.push({id:'dailygift|'+date,type:'dailyreward',value:50,name:'Daily Gift',source:'Daily Reward',rarity:'currency',earnedAt:date});reward={type:'coins',value:50,name:'Daily Gift +50 TURF Coins',rarity:'currency'};}else if(kind==='pack'){if(state.packClaimed)return {profile:a.profile,state,alreadyClaimed:true};let rarity=pickWeighted(FREE_PACK_ODDS),pool=CARD_CATALOG.filter(c=>c.rarity===rarity);if(!pool.length)pool=CARD_CATALOG.filter(c=>c.rarity==='common');const unowned=pool.filter(c=>!collection.includes(c.id)),c=(unowned.length?unowned:pool)[Math.floor(Math.random()*(unowned.length?unowned:pool).length)];if(collection.includes(c.id)){const d=duplicateCoins(c.rarity);coins+=d;reward={type:'card',value:c.id,name:c.name,set:c.set,rarity:c.rarity,duplicate:true,duplicateCoins:d,source:'Duplicate Conversion'};}else{collection.push(c.id);reward={type:'card',value:c.id,name:c.name,set:c.set,rarity:c.rarity,duplicate:false};}inv.push({id:'freepack|'+date,type:'dailyreward',value:'freepack',name:'Free Daily Pack',source:'Daily Reward',rarity:'common',earnedAt:date});const sr=setCompletion(collection,inv,coins);inv=sr.inventory;coins=sr.coins;}else throw new HttpError(400,'Unknown daily reward.');a.row[14]=coins;a.row[15]=JSON.stringify(inv);a.row[21]=JSON.stringify(collection);const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,state:dailyState(a.row),reward,pack:{id:'free_daily',name:'Free Daily Pack',art:'free',rarity:'common',odds:'free'}};}
async function getCollections(token,env){const a=await loadAccountForMutation(token,env),sets={};for(const c of CARD_CATALOG)(sets[c.set]||(sets[c.set]=[])).push(c);const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,owned:parseJsonArray(a.row[21]),sets,setMeta:SET_META};}
async function purchaseShopItem(payload,env){payload=payload||{};const item=SHOP_CATALOG[String(payload.itemId||'')];if(!item)throw new HttpError(404,'Shop item not found.');const a=await loadAccountForMutation(payload.token,env);let inv=parseJsonArray(a.row[15]),coins=Number(a.row[14]||0);if(inv.some(x=>x?.source==='shop'&&x.shopId===item.id))return {profile:a.profile,purchased:null,alreadyOwned:true};if(coins<Number(item.price))throw new HttpError(409,'Not enough TURF Coins.');coins-=Number(item.price);const x={id:'shop|'+item.id,shopId:item.id,type:item.type,value:item.value,name:item.name,source:'shop',rarity:item.rarity,price:item.price,earnedAt:pacificDate()};inv.push(x);a.row[14]=coins;a.row[15]=JSON.stringify(inv);const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,purchased:x,alreadyOwned:false};}
async function openPack(payload,env){payload=payload||{};const pack=PACK_CATALOG[String(payload.packId||'')];if(!pack)throw new HttpError(404,'Pack not found.');const a=await loadAccountForMutation(payload.token,env);let coins=Number(a.row[14]||0),inv=parseJsonArray(a.row[15]),collection=parseJsonArray(a.row[21]);if(coins<Number(pack.price))throw new HttpError(409,'INSUFFICIENT_BALANCE');coins-=Number(pack.price);let rewards=[];if(pack.kind==='avatar'){const pool=Object.values(SHOP_CATALOG).filter(x=>x.type==='avatar'&&!inv.some(i=>i?.type==='avatar'&&i.value===x.value));if(!pool.length){coins+=150;rewards.push({type:'coins',value:150,name:'Duplicate Protection +150 Coins',rarity:'currency'});}else{const av=pool[Math.floor(Math.random()*pool.length)],it={id:'pack|'+Date.now(),type:'avatar',value:av.value,name:av.name,source:'Pack',rarity:av.rarity};inv.push(it);rewards.push(it);}}else{for(const slot of (pack.slotPlan||Array(Number(pack.count||1)).fill('rookie'))){const c=randomCard(collection,slot);if(collection.includes(c.id)){const d=duplicateCoins(c.rarity);coins+=d;rewards.push({type:'card',value:c.id,name:c.name,set:c.set,rarity:c.rarity,duplicate:true,duplicateCoins:d,source:'Duplicate Conversion'});}else{collection.push(c.id);rewards.push({type:'card',value:c.id,name:c.name,set:c.set,rarity:c.rarity,duplicate:false});}}}const sr=setCompletion(collection,inv,coins);coins=sr.coins;inv=sr.inventory;rewards=rewards.concat(sr.bonus);a.row[14]=coins;a.row[15]=JSON.stringify(inv);a.row[21]=JSON.stringify(collection);const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,rewards,pack};}
async function updateCosmetic(payload,env){payload=payload||{};const a=await loadAccountForMutation(payload.token,env),type=String(payload.type||''),value=String(payload.value||''),inv=parseJsonArray(a.row[15]);if(value&&!inv.some(x=>x?.type===type&&x.value===value))throw new HttpError(403,'That cosmetic has not been unlocked.');if(type==='ring')a.row[16]=value;else if(type==='banner')a.row[17]=value;else if(type==='title')a.row[13]=value;else if(type==='avatar')a.row[9]=value;else throw new HttpError(400,'Unknown cosmetic type.');grantPassCoins(a.row);return saveAccountRow(env,a.sheetRow,a.row);}
async function awardAchievements(payload,env){payload=payload||{};const a=await loadAccountForMutation(payload.token,env),ids=Array.isArray(payload.achievementIds)?payload.achievementIds.map(String):[],known=parseJsonArray(a.row[12]),set=new Set(known);let awarded=[],bonus=0;for(const id of ids){const v=Number(ACHIEVEMENT_BONUSES[id]||0);if(!v||set.has(id))continue;set.add(id);known.push(id);awarded.push(id);bonus+=v;}if(bonus){a.row[3]=Number(a.row[3]||0)+bonus;a.row[12]=JSON.stringify(known);grantPassCoins(a.row);}const profile=await saveAccountRow(env,a.sheetRow,a.row);return {profile,awarded,bonus};}
async function updateTitle(payload,env){payload=payload||{};const a=await loadAccountForMutation(payload.token,env),title=String(payload.title||'').trim(),level=levelFromPoints(Number(a.row[3]||0));if(title&&level<Number(TITLE_LEVELS[title]||999))throw new HttpError(403,'That title has not been unlocked yet.');a.row[13]=title;return saveAccountRow(env,a.sheetRow,a.row);}
async function updateAvatar(payload,env){payload=payload||{};const a=await loadAccountForMutation(payload.token,env),url=String(payload.avatarUrl||''),emoji=String(payload.avatarEmoji||'').slice(0,16);if(url.length>500000)throw new HttpError(413,'Profile image is too large.');a.row[8]=url;a.row[9]=emoji;return saveAccountRow(env,a.sheetRow,a.row);}
async function submitDailyResult(payload,env){payload=payload||{};const token=cleanToken(payload.token),username=cleanUsername(payload.username),date=String(payload.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new HttpError(400,'Invalid Daily date.');const game=String(payload.game||''),pts=Number(GAME_POINTS[game]||0);if(!pts)throw new HttpError(400,'That game does not award Daily leaderboard points.');let a=await findAccountByToken(token,env);if(!a){await registerAccount(username,token,env);a=await findAccountByToken(token,env);}if(usernameKey(a.row[1])!==usernameKey(username))throw new HttpError(409,'Account username does not match this device token.');await ensureSheet(env,'FootballHQ_DailyLog',['AwardKey','Token','Username','Date','Game','Points']);const key=token+'|'+date+'|'+game,logs=await sheetValues(env,'FootballHQ_DailyLog!A2:F');if(logs.some(r=>String(r[0]||'')===key))return a.profile;grantWelcome(a.row);let streak=Number(a.row[5]||0),last=String(a.row[6]||'');if(last!==date){streak=last===addDaysDateKey(date,-1)?streak+1:1;last=date;}a.row[3]=Number(a.row[3]||0)+pts;a.row[4]=Number(a.row[4]||0)+1;a.row[5]=streak;a.row[6]=last;a.row[14]=Number(a.row[14]||0)+Number(GAME_COINS[game]||0);a.row[19]=Number(a.row[19]||a.row[4]||0)+1;a.row[20]=true;grantPassCoins(a.row);const profile=await saveAccountRow(env,a.sheetRow,a.row);await appendValues(env,'FootballHQ_DailyLog!A:F',[[key,token,a.row[1],date,game,pts]]);return profile;}
