import {HttpError,cleanToken,cleanUsername,usernameKey,accountsSheet,authSheet,sheetValues,appendValues,updateRange,findAccountByToken,findAccountByUsername} from './common.js';

const METHODS=new Set(['turfBatch1GoogleSignIn','turfBatch1BContinueAsGuest','turfBatch1BResolveAccountToken','getFootballHQAccount','resolveFootballHQBrowserIdentity']);
export function handlesAuthRpc(m){return METHODS.has(String(m||''));}
export async function handleAuthRpc(method,args,env){
  switch(String(method||'')){
    case 'turfBatch1GoogleSignIn':return googleSignIn(String(args?.[0]||''),env);
    case 'turfBatch1BContinueAsGuest':return continueAsGuest(String(args?.[0]||''),env);
    case 'turfBatch1BResolveAccountToken':return resolveAccountToken(String(args?.[0]||''),env);
    case 'getFootballHQAccount':{let a;try{a=await findAccountByToken(String(args?.[0]||''),env)}catch{return null}return a?.profile||null;}
    case 'resolveFootballHQBrowserIdentity':return resolveBrowserIdentity(args?.[0],args?.[1],env);
    default:return null;
  }
}
async function googleSignIn(idToken,env){const g=await verifyGoogleIdToken(idToken,env);const protectedMap=parseProtectedMap(env.PROTECTED_GOOGLE_MAP_JSON);const protectedUsername=protectedMap[g.email];if(protectedUsername){const target=await findAccountByUsername(protectedUsername,env);if(!target)throw new HttpError(409,'Protected TURF account could not be found.');await upsertAuthMapping(g,target.profile,env);return {ok:true,signedIn:true,linked:true,repaired:true,created:false,email:g.email,profile:target.profile};}const rows=await sheetValues(env,`${authSheet(env)}!A2:G`);const i=rows.findIndex(r=>String(r[0]||'')==='google'&&String(r[1]||'')===g.subject);if(i<0)return {ok:true,signedIn:false,needsLink:true,email:g.email,displayName:g.name};const token=String(rows[i][3]||'').trim();const account=token?await findAccountByToken(token,env):null;if(!account)throw new HttpError(409,'Your linked TURF account could not be found.');await updateRange(env,`${authSheet(env)}!G${i+2}:G${i+2}`,[[new Date().toISOString()]]);return {ok:true,signedIn:true,needsLink:false,email:g.email,profile:account.profile};}
async function continueAsGuest(rawToken,env){const token=cleanToken(rawToken);let a=await findAccountByToken(token,env);if(a)return {ok:true,mode:'guest',created:false,profile:a.profile};const rows=await sheetValues(env,`${accountsSheet(env)}!A2:W`),keys=new Set(rows.map(r=>usernameKey(r[1])));const tail=token.replace(/[^A-Za-z0-9]/g,'').slice(-6).toUpperCase()||crypto.randomUUID().replace(/-/g,'').slice(0,6).toUpperCase();let username=cleanUsername('Guest-'+tail);for(let n=2;keys.has(usernameKey(username))&&n<1000;n++)username=cleanUsername(('Guest-'+tail+'-'+n).slice(0,20));const row=[token,username,usernameKey(username),0,0,0,'',new Date().toISOString(),'','','','','[]','',0,'[]','','','[]',0,true,'[]',''];await appendValues(env,`${accountsSheet(env)}!A:W`,[row]);a=await findAccountByToken(token,env);if(!a)throw new HttpError(500,'Guest account creation failed.');return {ok:true,mode:'guest',created:true,profile:a.profile};}
async function resolveAccountToken(rawToken,env){try{const a=await findAccountByToken(cleanToken(rawToken),env);return a?{authenticated:true,profile:a.profile}:{authenticated:false,profile:null};}catch{return {authenticated:false,profile:null};}}
async function resolveBrowserIdentity(tokens,usernameHint,env){const arr=Array.isArray(tokens)?tokens.map(x=>String(x||'').trim()).filter(Boolean):[];for(const token of arr){try{const a=await findAccountByToken(token,env);if(a)return a.profile;}catch{}}const hint=String(usernameHint||'').trim();if(!hint||/^Guest-/i.test(hint))return null;try{return (await findAccountByUsername(hint,env))?.profile||null}catch{return null}}
async function upsertAuthMapping(g,profile,env){const rows=await sheetValues(env,`${authSheet(env)}!A2:G`),i=rows.findIndex(r=>String(r[0]||'')===g.provider&&String(r[1]||'')===g.subject),now=new Date().toISOString();if(i>=0){await updateRange(env,`${authSheet(env)}!A${i+2}:G${i+2}`,[[g.provider,g.subject,g.email,profile.token,profile.username,rows[i][5]||now,now]])}else await appendValues(env,`${authSheet(env)}!A:G`,[[g.provider,g.subject,g.email,profile.token,profile.username,now,now]]);}
function parseProtectedMap(raw){if(!raw)return {};try{const x=JSON.parse(raw),o={};Object.entries(x||{}).forEach(([e,u])=>o[String(e).toLowerCase().trim()]=String(u).trim());return o}catch{throw new HttpError(503,'Protected account mapping is misconfigured.')}}
async function verifyGoogleIdToken(idToken,env){idToken=String(idToken||'').trim();if(!idToken)throw new HttpError(400,'Missing Google ID token.');const r=await fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(idToken));if(!r.ok)throw new HttpError(401,'Google sign-in could not be verified.');const p=await r.json();if(String(p.aud||'')!==String(env.TURF_GOOGLE_CLIENT_ID||''))throw new HttpError(401,'Google sign-in audience mismatch.');if(String(p.email_verified||'')!=='true')throw new HttpError(401,'Google email is not verified.');return {provider:'google',subject:String(p.sub||''),email:String(p.email||'').toLowerCase().trim(),name:String(p.name||'')};}
