export class HttpError extends Error { constructor(status,message){ super(message); this.status=status; } }
export function safeError(err){ return String(err?.message||err||'TURF backend error.').slice(0,400); }
export function allowedOrigins(env){ return new Set(String(env.ALLOWED_ORIGINS||'https://turftrials.com').split(',').map(v=>v.trim()).filter(Boolean)); }
export function corsHeaders(origin,env,extra={}){ const h={'content-type':'application/json; charset=utf-8','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-turf-admin-key','access-control-max-age':'86400','vary':'Origin','cache-control':'no-store',...extra}; if(origin&&allowedOrigins(env).has(origin))h['access-control-allow-origin']=origin; return h; }
export function json(value,status=200,headers={}){ return new Response(JSON.stringify(value),{status,headers}); }
export function requireOrigin(origin,env){ if(!origin||!allowedOrigins(env).has(origin))throw new HttpError(403,'Origin is not allowed.'); }
export function cleanToken(v){ const t=String(v||'').trim(); if(!t||t.length<8||t.length>120)throw new HttpError(400,'Invalid account token.'); return t; }
export function cleanUsername(v){ const n=String(v||'').trim().replace(/\s+/g,' '); if(!/^[A-Za-z0-9_ -]{3,20}$/.test(n))throw new HttpError(400,'Username must be 3–20 letters, numbers, spaces, _ or -.'); return n; }
export function usernameKey(v){ return String(v||'').trim().toLowerCase().replace(/\s+/g,' '); }
export function parseJsonArray(v){ try{const x=JSON.parse(String(v||'[]'));return Array.isArray(x)?x:[];}catch{return [];} }
export function pacificDate(d=new Date()){ return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(d); }
export function addDaysDateKey(key,days){ const d=new Date(key+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10); }
export function levelRequirement(level){ level=Math.max(1,Number(level)||1); return 40+level*10+Math.floor(level/5)*15; }
export function pointsForLevel(level){let total=0;for(let l=1;l<Math.max(1,Number(level)||1);l++)total+=levelRequirement(l);return total;}
export function levelFromPoints(points){points=Math.max(0,Number(points)||0);let level=1;while(level<100&&points>=pointsForLevel(level+1))level++;return level;}
export function accountObject(row){ row=Array.isArray(row)?row:[]; const achievementIds=parseJsonArray(row[12]),inventory=parseJsonArray(row[15]),claims=parseJsonArray(row[18]); const points=Number(row[3]||0),totalDailies=Number(row[4]||0); const welcomeItem=inventory.find(x=>x&&(x.id==='welcome|v79'||x.id==='welcome|v78')); return {token:String(row[0]||''),username:String(row[1]||''),points,totalDailies,streakDays:Number(row[5]||0),lastDailyDate:normalizeDateCell(row[6]),avatarUrl:String(row[8]||''),avatarEmoji:String(row[9]||''),achievementIds,equippedTitle:String(row[13]||''),hqCoins:Number(row[14]||0),inventory,equippedRing:String(row[16]||''),equippedBanner:String(row[17]||''),placementClaims:claims,dailyWins:Number(row[19]||totalDailies||0),collection:parseJsonArray(row[21]),lastCoinAward:String(row[22]||''),level:levelFromPoints(points),welcomePending:!!(welcomeItem&&welcomeItem.presented!==true&&points===0&&totalDailies===0)}; }
export function normalizeDateCell(v){ const s=String(v||'').trim(); const m=s.match(/^\d{4}-\d{2}-\d{2}/); return m?m[0]:s; }
export function accountsSheet(env){return String(env.ACCOUNTS_SHEET||'FootballHQ_Accounts');}
export function authSheet(env){return String(env.AUTH_SHEET||'TURF_Auth');}
export async function readAccounts(env){return sheetValues(env,`${accountsSheet(env)}!A2:W`);}
export async function findAccountByToken(token,env){token=cleanToken(token);const rows=await readAccounts(env);const i=rows.findIndex(r=>String(r[0]||'')===token);return i<0?null:{index:i,sheetRow:i+2,row:padRow(rows[i]),profile:accountObject(rows[i])};}
export async function findAccountByUsername(username,env){const key=usernameKey(cleanUsername(username)),rows=await readAccounts(env);const i=rows.findIndex(r=>usernameKey(r[2]||r[1])===key);return i<0?null:{index:i,sheetRow:i+2,row:padRow(rows[i]),profile:accountObject(rows[i])};}
export function padRow(row){const out=Array.isArray(row)?row.slice():[];while(out.length<23)out.push('');return out.slice(0,23);}
export async function saveAccountRow(env,sheetRow,row){row=padRow(row);row[7]=new Date().toISOString();await updateRange(env,`${accountsSheet(env)}!A${sheetRow}:W${sheetRow}`,[row]);return accountObject(row);}
export async function ensureSheet(env,title,headers){ const token=await serviceAccountAccessToken(env);const metaUrl=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.TURF_SPREADSHEET_ID)}?fields=sheets.properties.title`;const mr=await fetch(metaUrl,{headers:{authorization:`Bearer ${token}`}});const meta=await mr.json().catch(()=>({}));if(!mr.ok)throw new HttpError(502,meta?.error?.message||'Google Sheets metadata read failed.');if(!(meta.sheets||[]).some(s=>s?.properties?.title===title)){const u=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.TURF_SPREADSHEET_ID)}:batchUpdate`;const r=await fetch(u,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({requests:[{addSheet:{properties:{title}}}]})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new HttpError(502,b?.error?.message||'Could not create TURF sheet.');}const first=await sheetValues(env,`${title}!A1:${colLetter(headers.length)}1`);if(!first.length||headers.some((h,i)=>String(first[0]?.[i]||'')!==h))await updateRange(env,`${title}!A1:${colLetter(headers.length)}1`,[headers]); }
export function colLetter(n){let s='';while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
export async function sheetValues(env,range){const token=await serviceAccountAccessToken(env);const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.TURF_SPREADSHEET_ID)}/values/${encodeURIComponent(range)}?majorDimension=ROWS&valueRenderOption=UNFORMATTED_VALUE`;const res=await fetch(url,{headers:{authorization:`Bearer ${token}`}});const body=await res.json().catch(()=>({}));if(!res.ok)throw new HttpError(502,body?.error?.message||'Google Sheets read failed.');return Array.isArray(body.values)?body.values:[];}
export async function appendValues(env,range,values){const token=await serviceAccountAccessToken(env);const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.TURF_SPREADSHEET_ID)}/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`;const res=await fetch(url,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new HttpError(502,body?.error?.message||'Google Sheets append failed.');return body;}
export async function updateRange(env,range,values){const token=await serviceAccountAccessToken(env);const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.TURF_SPREADSHEET_ID)}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`;const res=await fetch(url,{method:'PUT',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new HttpError(502,body?.error?.message||'Google Sheets update failed.');return body;}
export async function clearRange(env,range){const token=await serviceAccountAccessToken(env);const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(env.TURF_SPREADSHEET_ID)}/values/${encodeURIComponent(range)}:clear`;const res=await fetch(url,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:'{}'});const body=await res.json().catch(()=>({}));if(!res.ok)throw new HttpError(502,body?.error?.message||'Google Sheets clear failed.');return body;}
let cachedAccessToken='',cachedAccessTokenExp=0;
export async function serviceAccountAccessToken(env){const now=Math.floor(Date.now()/1000);if(cachedAccessToken&&cachedAccessTokenExp>now+60)return cachedAccessToken;const header=b64url(JSON.stringify({alg:'RS256',typ:'JWT'}));const claim=b64url(JSON.stringify({iss:String(env.GOOGLE_SERVICE_ACCOUNT_EMAIL),scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const unsigned=`${header}.${claim}`,key=await importPrivateKey(String(env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY));const sig=await crypto.subtle.sign({name:'RSASSA-PKCS1-v1_5'},key,new TextEncoder().encode(unsigned));const assertion=`${unsigned}.${b64urlBytes(new Uint8Array(sig))}`;const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});const body=await res.json().catch(()=>({}));if(!res.ok||!body.access_token)throw new HttpError(502,body.error_description||'Could not authorize Google Sheets service account.');cachedAccessToken=body.access_token;cachedAccessTokenExp=now+Number(body.expires_in||3600);return cachedAccessToken;}
async function importPrivateKey(pem){pem=pem.replace(/\\n/g,'\n').replace(/-----BEGIN PRIVATE KEY-----/g,'').replace(/-----END PRIVATE KEY-----/g,'').replace(/\s+/g,'');const bytes=Uint8Array.from(atob(pem),c=>c.charCodeAt(0));return crypto.subtle.importKey('pkcs8',bytes.buffer,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);}
function b64url(text){return b64urlBytes(new TextEncoder().encode(text));}function b64urlBytes(bytes){let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
