import {HttpError,ensureSheet,sheetValues,appendValues,updateRange} from './common.js';
const METHODS=new Set(['createDraftRoom','joinDraftRoom','getDraftRoom','startDraftRoom','submitDraftPick','submitCpuDraftPick','submitTimedAutoPick','postDraftChat']);
const TTL=24*60*60*1000;
export function handlesDraftRpc(m){return METHODS.has(String(m||''));}
export async function handleDraftRpc(method,args,env){switch(String(method||'')){
 case 'createDraftRoom':return createRoom(args?.[0],args?.[1],env);
 case 'joinDraftRoom':return joinRoom(args?.[0],args?.[1],env);
 case 'getDraftRoom':return getRoom(args?.[0],args?.[1],env);
 case 'startDraftRoom':return startRoom(args?.[0],args?.[1],env);
 case 'submitDraftPick':return submitPick(args?.[0],args?.[1],args?.[2],env,false,false);
 case 'submitCpuDraftPick':return submitPick(args?.[0],args?.[1],args?.[2],env,true,false);
 case 'submitTimedAutoPick':return submitPick(args?.[0],args?.[1],args?.[2],env,true,true);
 case 'postDraftChat':return postChat(args?.[0],args?.[1],args?.[2],env);
 default:return null;}}
function sheet(env){return String(env.DRAFT_ROOMS_SHEET||'DraftRooms');}
async function rows(env){await ensureSheet(env,sheet(env),['RoomCode','StateJSON','UpdatedAt']);return sheetValues(env,`${sheet(env)}!A2:C`);}
function code(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);}
function cleanName(v,fallback){const n=String(v||'').replace(/[<>]/g,'').trim().slice(0,24);return n||fallback;}
function clamp(v,min,max,fallback){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):fallback;}
function playerKey(v){return String(v||'').toLowerCase().replace(/[.’']/g,'').replace(/[^a-z0-9]/g,'');}
async function load(roomCode,env){const c=code(roomCode);if(!c)return null;const rs=await rows(env),i=rs.findIndex(r=>String(r[0]||'')===c);if(i<0)return null;try{const st=JSON.parse(String(rs[i][1]||''));if(Date.now()-Number(st.updatedAt||st.createdAt||0)>TTL)return null;return {state:st,row:i+2};}catch{return null;}}
async function save(st,env,row){st.updatedAt=Date.now();if(row)await updateRange(env,`${sheet(env)}!A${row}:C${row}`,[[st.code,JSON.stringify(st),new Date().toISOString()]]);else await appendValues(env,`${sheet(env)}!A:C`,[[st.code,JSON.stringify(st),new Date().toISOString()]]);return st;}
async function uniqueCode(env){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',rs=await rows(env),used=new Set(rs.map(r=>String(r[0]||'')));for(let a=0;a<30;a++){let c='';for(let i=0;i<6;i++)c+=alphabet[Math.floor(Math.random()*alphabet.length)];if(!used.has(c))return c;}throw new HttpError(500,'Could not create a unique room code.');}
function memberByToken(st,t){return (st.participants||[]).find(p=>p.token===t)||null;}function memberBySlot(st,s){return (st.participants||[]).find(p=>Number(p.slot)===Number(s))||null;}
function snake(overall,teams){const round=Math.floor((overall-1)/teams)+1,pickInRound=((overall-1)%teams)+1,teamSlot=round%2?pickInRound:teams-pickInRound+1;return {round,pickInRound,teamSlot,label:round+'.'+String(pickInRound).padStart(2,'0')};}
function publicState(st,token){const you=memberByToken(st,token);return {code:st.code,status:st.status,teams:st.teams,rounds:st.rounds,hostId:st.hostId,participants:(st.participants||[]).map(p=>({id:p.id,name:p.name,slot:p.slot,isHost:!!p.isHost})),overallPick:st.overallPick,picks:st.picks||[],chat:st.chat||[],turnStartedAt:st.turnStartedAt,updatedAt:st.updatedAt,you:you?{id:you.id,name:you.name,slot:you.slot,isHost:!!you.isHost,token}:null};}
async function createRoom(hostName,settings,env){settings=settings||{};const teams=clamp(settings.teams,8,14,12),roundsN=clamp(settings.rounds,1,20,13),slot=clamp(settings.slot,1,teams,1),c=await uniqueCode(env),token=crypto.randomUUID(),id=crypto.randomUUID().slice(0,8),now=Date.now(),st={version:1,code:c,status:'lobby',teams,rounds:roundsN,hostId:id,participants:[{id,token,name:cleanName(hostName,'Host'),slot,isHost:true,joinedAt:now}],overallPick:1,picks:[],chat:[],createdAt:now,updatedAt:now,turnStartedAt:null};await save(st,env);return publicState(st,token);}
async function joinRoom(roomCode,managerName,env){const x=await load(roomCode,env);if(!x)throw new HttpError(404,'Room not found. Check the code and try again.');const st=x.state;if(st.status!=='lobby')throw new HttpError(409,'That draft has already started.');if((st.participants||[]).length>=st.teams)throw new HttpError(409,'That draft room is full.');const used=new Set((st.participants||[]).map(p=>Number(p.slot)));let slot=1;while(slot<=st.teams&&used.has(slot))slot++;if(slot>st.teams)throw new HttpError(409,'No draft slots are available.');const token=crypto.randomUUID(),id=crypto.randomUUID().slice(0,8);st.participants.push({id,token,name:cleanName(managerName,'Manager'),slot,isHost:false,joinedAt:Date.now()});await save(st,env,x.row);return publicState(st,token);}
async function getRoom(roomCode,token,env){const x=await load(roomCode,env);if(!x)throw new HttpError(404,'Room not found or expired.');return publicState(x.state,String(token||''));}
async function requireMember(roomCode,token,env){const x=await load(roomCode,env);if(!x)throw new HttpError(404,'Room not found or expired.');if(!memberByToken(x.state,String(token||'')))throw new HttpError(403,'You are no longer a member of this room.');return x;}
async function startRoom(roomCode,token,env){const x=await requireMember(roomCode,token,env),st=x.state,m=memberByToken(st,String(token));if(!m?.isHost)throw new HttpError(403,'Only the room host can start the draft.');if(st.status!=='lobby')return publicState(st,String(token));st.status='drafting';st.overallPick=1;st.picks=[];st.turnStartedAt=Date.now();await save(st,env,x.row);return publicState(st,String(token));}
function addPick(st,pick,info,managerName,auto){pick=pick||{};const key=playerKey(pick.key||pick.player||pick.name);if(!key)throw new HttpError(400,'Invalid player selection.');if((st.picks||[]).some(p=>p.key===key))throw new HttpError(409,'That player was already drafted.');st.picks.push({key,name:String(pick.name||pick.player||'Player').slice(0,80),position:String(pick.position||'').toUpperCase().slice(0,8),team:String(pick.team||'').toUpperCase().slice(0,8),teamSlot:info.teamSlot,overallPick:st.overallPick,pickLabel:info.label,autoPicked:!!auto,managerName});st.overallPick++;st.turnStartedAt=Date.now();if(st.overallPick>st.teams*st.rounds){st.status='complete';st.turnStartedAt=null;}}
async function submitPick(roomCode,token,pick,env,hostMode,timed){const x=await requireMember(roomCode,token,env),st=x.state,m=memberByToken(st,String(token));if(st.status!=='drafting')throw new HttpError(409,'The draft is not active.');const info=snake(st.overallPick,st.teams);if(hostMode){if(!m?.isHost)throw new HttpError(403,timed?'Only the host device can process timed auto-picks.':'Only the host device can advance CPU picks.');if(timed){const elapsed=Date.now()-Number(st.turnStartedAt||Date.now());if(elapsed<59000)throw new HttpError(409,'The pick clock has not expired yet.');const human=memberBySlot(st,info.teamSlot);addPick(st,pick,info,human?human.name:'CPU '+info.teamSlot,true);}else{if(memberBySlot(st,info.teamSlot))throw new HttpError(409,'That draft slot belongs to a human manager.');addPick(st,pick,info,'CPU '+info.teamSlot,false);}}else{if(!m||Number(m.slot)!==Number(info.teamSlot))throw new HttpError(409,'It is not your turn.');addPick(st,pick,info,m.name,false);}await save(st,env,x.row);return publicState(st,String(token));}
function filterChat(text){const blocked=['fuck','fucking','fucked','fucker','shit','shitty','bitch','bitches','asshole','dick','cunt','motherfucker','motherfucking','bastard','slut','whore','retard','retarded'];let out=String(text||'');for(const word of blocked.sort((a,b)=>b.length-a.length)){const e=word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp('(^|[^a-z0-9])('+e+')(?=$|[^a-z0-9])','gi'),(m,p)=>p+'***');}return out;}
async function postChat(roomCode,token,text,env){const x=await requireMember(roomCode,token,env),st=x.state,m=memberByToken(st,String(token)),clean=filterChat(String(text||'').replace(/[<>]/g,'')).trim().slice(0,220);if(!clean)return publicState(st,String(token));st.chat=Array.isArray(st.chat)?st.chat:[];st.chat.push({id:crypto.randomUUID().slice(0,10),memberId:m.id,name:m.name,text:clean,at:Date.now()});if(st.chat.length>100)st.chat=st.chat.slice(-100);await save(st,env,x.row);return publicState(st,String(token));}
