name = "turftest-api"
main = "index.js"
compatibility_date = "2026-08-23"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://turftrials.com"
ACCOUNTS_SHEET = "FootballHQ_Accounts"
AUTH_SHEET = "TURF_Auth"
DRAFT_ROOMS_SHEET = "DraftRooms"
